name: Continuous deployment
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build
        run: wasm-pack build --target web "$INPUT_PATH"
        env:
          INPUT_PATH: ${{ inputs.path }}

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Remove the .gitignore idk why lol
      #   run: rm -f "$INPUT_PATH/pkg/.gitignore"
      #   env:
      #     INPUT_PATH: ${{ inputs.path }}

      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ${{ inputs.path }}

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          